# Generated by Django 4.1.3 on 2023-05-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='test_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='result',
            name='quest_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
